### PR TITLE
BFS: Improve model solution queue

### LINKED ISSUE #246: BFS: improve model answer queue
The queue in the model answer should be improved.

- [x] Add queued nodes to the rear of the queue (right end) and dequeue them from front (left end). Example visualization [here](https://tarjotin.cs.aalto.fi/cs-a1141/OpenDSA/Books/CS-A1141/html/QueueLinked.html).
- [x] Add legend for queue

### PR DESCRIPTION
**Pull request by ttaiv**
Queue is now implemented with a linked list that has a header node and front and rear pointers.

Closes #246

### CODE REVIEW

**Comment by ttaiv** [comment]
Archie proposed that the course material could have a note telling that this exercise uses [OpenDSA notation of the linked queue](https://tarjotin.cs.aalto.fi/cs-a1141/OpenDSA/Books/CS-A1141/html/QueueLinked.html).

**Review by atilante — CHANGES_REQUESTED** [review]
The linked list queue looks very nice and seems be according to Archie's request.

Could you still improve the model answer layout a bit? See the image below.

BFS-queue-as-list

1. The model answer window is rather wide, 1800 pixels.
2. The vertical queue-as-list could be placed over the graph view. See my draft below.

BFS-queue-as-list-draft

Notice how the size of the model answer is 600x700 pixels with this design. Because the start node A is always at top-right corner and the graph is a planar graph on a 4x4 square grid, the length of the queue should not exceed five elements. I would say that the graph in the image above is an example of a maximally wide BFS tree with maximum length of the queue at the moment. Therefore the model answer does need to be wider than that to fit the queue, unless the exercise is changed so that the number of nodes and edges in the graph template increases.

**Comment by ttaiv** [comment]
I improved the positioning of the model queue as suggested. I agree that this looks better. But is it possible to somehow manually control the size of the model answer window? And should I adjust it if possible?

**Comment by atilante** [comment]
> I improved the positioning of the model queue as suggested. I agree that this looks better. But is it possible to somehow manually control the size of the model answer window? And should I adjust it if possible?

The user cannot control the size of the model answer window. I actually fixed the size of the model answer dialog to 600x900.

**Review by atilante — APPROVED** [review]

**Pull request merged**
