### PR TITLE
Open hashing improvements

### PR DESCRIPTION
**Pull request by ttaiv**
Ensured the uniqueness of hash table keys even though I was not able to replicate the bug mentioned in #230. Also improved the model answer by adding a separate step for calculating the index of the current key.

Related to #230

### CODE REVIEW

**Comment by ttaiv** [comment]
How big of an improvement would it be to highlight all the click operations in the model answer as suggested in #230? The same issue also mentions that GUI operations are a bit different depending on whether the hash table is empty or not.

**Review by atilante — CHANGES_REQUESTED** [review]
The selection procedure for unique values is OK.

hashing-model-solution
Model answer: in the last step of a list search, the yellow highlight flashes only for a moment. E.g. in the figure above, at model answer step 19, highlight at node with value 525 stays until the next step, while at step 20, the node with value 426 flashes briefly with yellow. This is easy to miss and not consistent with previous steps.

Proposal: at each list search step:
1. Remove highlight from previously highlighted list node, if that exists.
2. Highlight current node.
This would require that also other model answer steps clear previous node highlights if those exist. Solution: use a temporary variable, e.g. `previouslyHighlightedNode`.

**Comment by ttaiv** [comment]
Things to discuss
- Should only the last clicked node be highlighted or all clicked nodes (so that all nodes are unhighlighted after every operation)?
  - Currently all the nodes are highlighted in the user GUI.
- Should there be a separate step that highlights the node before applying operation to it?
  - If yes, should the first (empty) node be also highlighted when, for example, searching a key from an empty index?
- Should the user click the first (empty) node before the nodes with the payload?

**Comment by atilante** [comment]
Archie:
- yes: always click the initial location in the hash *table* (pointer read operation)
- yes, click all elements in the list until the target value is found
- yes, make the click operations and the model answer highlights consistent

**Comment by atilante** [comment]
Issue #229 is duplicate of this. Lets keep this issue and close #229

**Comment by ttaiv** [comment]
- [ ] always click the initial location in the hash table (pointer read operation)
- [ ] click all elements in the list until the target value is found
- [ ] make the click operations and the model answer highlights consistent
 - [ ] Model answer: when there is a pointer write operation (e.g. deleting a value), highlight it with red
 - [ ] The insertion should be done at the beginning of the list, not at the end of the list. (Less computationally expensive).
 - [ ] Highlight the hash table cell with green to indicate a pointer update.

**Comment by ttaiv** [comment]
I am now happy with how the exercise functions. However, I did not add red coloring for remove operation or green coloring for insert. I especially hesitated with adding red coloring to the model answer as it would add UI element that is not part of the student interface. Instead I aimed to make the model answer and the student UI as similar as possible. In the current version, yellow highlighting simply represents a click operation. The same highlights should be present in both UI and model.

**Review by atilante — APPROVED** [review]

**Comment by atilante** [comment]
I agree with your reasoning. Nice work as usual! Approved. Please integrate this version of the exercise into CS-A1141 course repo, then notify Archie.

**Pull request merged**
